### ISSUE TITLE
Move selection butons (✔️, ❌ and blank) to the left side of the UI in order to improve the erogonmics of Eddie

### ISSUE THREAD

**Issue by wdbm** [AirVPN/Eddie#107] opened 2020-10-04 03:59 UTC
As seen in the image below, the buttons (✔️, ❌ etc.) used to select countries (and to select servers in the *Servers* tab) are on the right-most side of the UI, far from where the user picks the country (or server).

![1987bbb3](https://user-images.githubusercontent.com/2429104/95006105-5f125f80-05f8-11eb-8d2d-7de0d80db694.png)

This means that users are forced to move the mouse pointer constantly from left of the UI to the right, and back again, to select countries or servers.

It could be argued that the buttons should be moved to the left (where they'd be present and consistent with other UI buttons) so this work isn't pushed on the user and the ergonomics is improved,

**Comment by AirVPN** [comment] 2021-01-19 13:45
Duplicate of https://github.com/AirVPN/Eddie/issues
We close this.

**Closed by AirVPN** 2021-01-19 13:45 UTC
Labels: duplicate
