### ISSUE TITLE
add indicator to ubuntu version

### ISSUE THREAD

**Issue by grrrrr** [AirVPN/Eddie#22] opened 2015-06-23 18:26 UTC
Hello,

Can it be possible to add an indicator applet to the Top menu bar (where network, sound, clock are).  And if possible have it be able to indicate the state of vpn connection like the network connection applet gets a lock when on VPN.

This would be allowing Ubuntu users to easily see if they are connected or not

**Comment by AirVPN** [comment] 2015-07-20 12:18
It's planned, but it's not easy. All UI must be rewritten in GTK, because the actual WinForms UI don't support applet in Mono/Linux.

**Comment by smacz42** [comment] 2015-12-28 06:41
I am glad to hear that this is planned. Is there way other than minimizing it to have the graphical front-end run in the background?

**Comment by rsm-gh** [comment] 2016-08-17 22:34
It is great to know that this is planned. 

I'm using the client on Debian and it would be great to be able of closing the window and just having an indicator in to the system try.

~The GTK interface sounds good :)

**Comment by AirVPN** [comment] 2020-06-25 12:26
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!

**Closed by AirVPN** 2020-06-25 12:26 UTC
